version: '3.8'

services:
  web:
    image: <account-id>.dkr.ecr.<region>.amazonaws.com/<repository-name>:<tag>
 # Placeholder; will replace in deploy step
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
