version: '3.8'
services:
  web:
    image: 190168171128.dkr.ecr.eu-central-1.amazonaws.com/sample:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
