version: "3.8"

services:
  node-service:
    image: 471112907169.dkr.ecr.us-east-1.amazonaws.com/node-base:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 2
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
